config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'terms_and_conditions', to: :show, controller: 'home'
  get 'privacy_policy', to: :show, controller: 'home'
  get 'download_csv', to: :show, controller: 'home'

  get "/checkout" => "checkout#index", as: :checkout
  post "/proceed-to-pay" => "payments#proceed_to_pay", as: :proceed_to_pay
  post "/order-processed" => "payments#order_processed", as: :order_processed
  get "/payment_success" => "payments#payment_success"

  resources :landing

  resources :events do
    resources :comments
  end
  resources :contact_admin do
    collection do
      post :contact
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone_event.rb
require 'csv'
class CloneEvent
  class << self
    def perform(event_id)
    	event = Event.find_by(id: event_id)
    	if event
	      event_dup = event.amoeba_dup
	      event_dup.parent_id = event.id
	      event_dup.document = event.document
	      event_dup.save
	      return event_dup
	    end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/csv_db.rb
require 'csv'
class CsvDb
  class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read.gsub /\r/, ''
      parser = CSV.parse(csv_file).to_a
      parsed_contents = parser[1..-1]
      headers = parser[0].map(&:underscore)
      parsed_contents.each do |row|
        params = Hash[headers.zip(row.map { |i| i.force_encoding('UTF-8') if i.present? })]
        event = Event.new(params)
        event.save
      end
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :event
  mount_uploader :image, DocumentUploader
end

app/models/event.rb
class Event < ApplicationRecord
	mount_uploader :document, DocumentUploader

  after_save :set_tentative_schedules
  before_save :set_event_details

  has_many :comments, as: :commentable
  has_many :tentative_schedules, dependent: :destroy

  belongs_to :parent, :class_name => "Event", optional: true
  has_many :events, dependent: :destroy, :foreign_key => "parent_id"

  has_many :pick_up_points, dependent: :destroy
  accepts_nested_attributes_for :pick_up_points, allow_destroy: true
  accepts_nested_attributes_for :tentative_schedules, allow_destroy: true
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :documents, allow_destroy: true
  has_one :instructor_detail, dependent: :destroy
  accepts_nested_attributes_for :instructor_detail, allow_destroy: true

  enum event_type: %w(event course expedition)
  enum status: %w(coming_soon bookings_open ongoing completed)
  enum month: %w(January February March April May June July August September October November December)

  scope :past, -> { where('start_date < ?', Date.current).where.not(parent_id: nil) }
  scope :on_going, -> { where('start_date = ?', Date.current).where.not(parent_id: nil) }
  scope :future, -> { where('start_date > ?', Date.current).where.not(parent_id: nil) }
  scope :parent_events, -> { where(parent_id: nil) }

  amoeba do
    enable
  end

  private

  def set_tentative_schedules
    if tentative_schedules.blank? && event_type == 'event'
      tentative_schedules.create(key: 'Friday',
                                 value: "09:30 PM Pick-up from Indiranagar ESI Hospital, 09:45 PM Pick-up from New Shanthi Sagar hotel Domlur, 10:00 PM Pick-up from Lifestyle, Magrath road")
      tentative_schedules.create(key: 'Saturday',
                                 value: "06:30 AM Reach the place - Freshen up - Breakfast, 09:30 AM Trek from Sarpadhari to Mullyangiri, 02:00 PM Reach and Have packed lunch. Trek down to Bababuddhangiri, 07:00 PM Reach base camp - Dinner - Night stay")
      tentative_schedules.create(key: 'Sunday',
                                 value: "06:00AM Pack up things and Leave to water falls Reach water falls base and have fun Start back to Bangalore, 10:00PM Reach Bangalore")
    end
  end

  def set_event_details
    if event_type == 'event' || event_type.nil?
      self.what_to_pack = "Personal medication (if any),Strong backpack (Preferably water proof),Fresh pair of clothes for two days,Toiletries,Mosquito Reppellent Cream" if self.what_to_pack.blank?
      self.inclusions = "Forest permission charges,Non A/C Transport from Bangalore to Bangalore,Accommodation,Veg Meals (2 Breakfast 1 lunch & 1 Dinner),Basic First aid Support,Instructor" if self.inclusions.blank?
      self.exclusions = "Sunday Lunch, Snacks During Transit,Anything not mentioned above in Inclusion" if self.exclusions.blank?
    end
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	mount_uploader :image, DocumentUploader
end

app/models/instructor_detail.rb
class InstructorDetail < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event
end

app/models/pick_up_point.rb
class PickUpPoint < ApplicationRecord
  belongs_to :event, optional: true
end

app/models/setting.rb
class Setting < ApplicationRecord
	mount_uploader :document, DocumentUploader
end

app/models/tentative_schedule.rb
class TentativeSchedule < ApplicationRecord
  belongs_to :event
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  has_one :user_payment_detail
  scope :success, -> { where(status: 'TXN_SUCCESS').order('created_at desc') }
  scope :failure, -> { where.not(status: 'TXN_SUCCESS') }
end

app/models/user.rb
class User < ApplicationRecord
	def full_name
		if last_name.present?
			name = first_name + " " + last_name
		else
			name = first_name
		end
		name
	end
end

app/models/user_payment_detail.rb
class UserPaymentDetail < ApplicationRecord
  belongs_to :payment_transaction, class_name: 'Transaction', foreign_key: :transaction_id, optional: true
  belongs_to :event
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  def index
    @event = Event.find(params[:event_id])
    @checkout_terms = Setting.find_by(key: 'checkout_terms')
    @pick_up_points = PickUpPoint.where(id: @event.picks)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :data_setting, only: %i(index)

  def terms_and_conditions
    @logo = Gallery.find_by(key: 'logo')
    @email = Setting.find_by(key: 'email').description
    @terms_and_conditions = Setting.find_by(key: 'terms_and_conditions')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def privacy_policy
    @email = Setting.find_by(key: 'email').description
    @logo = Gallery.find_by(key: 'logo')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def download_csv
    send_file(
      "#{Rails.root}/public/events_bulk.csv",
      filename: "events_bulk.csv"
    )
  end

  private

  def data_setting
    1.upto(3).map { |i| instance_variable_set("@highlights_#{i}", Setting.find_by(key: "Highlights#{i}")) }
    @email = Setting.find_by(key: 'email').description
    @address = Setting.find_by(key: 'address').description
    @contact_number = Setting.find_by(key: 'contact_number').description
    #1.upto(6).map { |i| instance_variable_set("@events_#{i}", Event.find_by(key: "Event#{i}")) }
    @events = Event.bookings_open.where.not(parent_id: nil)#.or(Event.coming_soon)
    1.upto(2).map { |i| instance_variable_set("@expedition_#{i}", Event.find_by(key: "Expedition#{i}")) }
    %w(who_we_are what_we_do from_whom_we_learn what_we_learn).each do |key|
    	instance_variable_set("@#{key}", Setting.find_by(key: key))
    end
    1.upto(6).map { |i| instance_variable_set("@gal_image_#{i}", Gallery.find_by(key: "GalImage#{i}")) }
    @gal_background = Gallery.find_by(key: "GalBackground")
    @logo = Gallery.find_by(key: 'logo')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_admin_helper.rb
module ContactAdminHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/checkout/index.html.erb
<%= form_tag proceed_to_pay_path do %>
  <%= hidden_field_tag 'event_id', @event.id %>
  <div class="checkout container">
    <div class="module-title-x font-alt">Checkout </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>First Name</label>
          <input type="text" class="form-control" id="name" name="first_name" placeholder="Name" required>
          <p class="error-msg">First Name is required</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>Last Name</label>
          <input type="text" class="form-control" id="Text1" name="last_name" placeholder="Last Name" required></div>
          <p class="error-msg">Last Name is required</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>Email  <span class="asteric">*</span></label>
          <input class="form-control" type="email" id="email" name="email" placeholder="Email" required>
          <p class="error-msg">Email is required</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>Mobile <span class="asteric">*</span></label>
          <input type=
        "text" class="form-control" id="mobile" name="mobile_number" placeholder="Mobile Number" required>
          <p class="error-msg">Mobile is required</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label>Head Count <span class="asteric">*</span></label>
          <input type=
        "text" class="form-control" id='head_count' name="head_count" placeholder="(1-10 people max)" required>
          <p class="error-msg">Head Count is required</p>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label>Pickup Point <span class="asteric">*</span></label>
          <select class="form-control" id="dc">
            <% @pick_up_points.each do |pick_up_point| %>
              <option><%= pick_up_point.name %></option>
            <% end %>
          </select>
          <p class="error-msg">Pickup is required</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <div class="form-group">
          <label>Your Commnts</label>
          <textarea class="form-control" id="exampleTextarea" rows="3" name="comments" placeholder="Post your queries"></textarea>
        </div>
      </div>
    </div>
    <div class="">
      <div class="col-sm-12 terms-accept form-group">
        <div class="custom-check">
          <input type="checkbox" id="c" name="box" required/>
          <label for="c"><strong><%= @checkout_terms.description %></strong></label>
        </div>
        <em>  </em>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12">
        <%= submit_tag 'Submit', :class => 'btn btn-primary pull-right' %>
        &nbsp;
        &nbsp;
        <button type = "reset" class ="btn-outline">Reset</button>
      </div>
    </div>
  </div>
</div>
<% end %>