config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'terms_and_conditions', to: :show, controller: 'home'
  get 'privacy_policy', to: :show, controller: 'home'
  get 'download_csv', to: :show, controller: 'home'

  get "/checkout" => "checkout#index", as: :checkout
  post "/proceed-to-pay" => "payments#proceed_to_pay", as: :proceed_to_pay
  post "/order-processed" => "payments#order_processed", as: :order_processed
  get "/payment_success" => "payments#payment_success"

  resources :landing

  resources :events do
    resources :comments
  end
  resources :contact_admin do
    collection do
      post :contact
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :data_setting, only: %i(index)

  def terms_and_conditions
    @logo = Gallery.find_by(key: 'logo')
    @email = Setting.find_by(key: 'email').description
    @terms_and_conditions = Setting.find_by(key: 'terms_and_conditions')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def privacy_policy
    @email = Setting.find_by(key: 'email').description
    @logo = Gallery.find_by(key: 'logo')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def download_csv
    send_file(
      "#{Rails.root}/public/events_bulk.csv",
      filename: "events_bulk.csv"
    )
  end

  private

  def data_setting
    1.upto(3).map { |i| instance_variable_set("@highlights_#{i}", Setting.find_by(key: "Highlights#{i}")) }
    @email = Setting.find_by(key: 'email').description
    @address = Setting.find_by(key: 'address').description
    @contact_number = Setting.find_by(key: 'contact_number').description
    #1.upto(6).map { |i| instance_variable_set("@events_#{i}", Event.find_by(key: "Event#{i}")) }
    @events = Event.bookings_open.where.not(parent_id: nil)#.or(Event.coming_soon)
    1.upto(2).map { |i| instance_variable_set("@expedition_#{i}", Event.find_by(key: "Expedition#{i}")) }
    %w(who_we_are what_we_do from_whom_we_learn what_we_learn).each do |key|
    	instance_variable_set("@#{key}", Setting.find_by(key: key))
    end
    1.upto(6).map { |i| instance_variable_set("@gal_image_#{i}", Gallery.find_by(key: "GalImage#{i}")) }
    @gal_background = Gallery.find_by(key: "GalBackground")
    @logo = Gallery.find_by(key: 'logo')
  end
end

app/views/home/index.html.erb
<section class="home-section home-full-height" id="home">
  <div class="hero-slider">
    <ul class="slides">
      <li class="bg-dark-30 restaurant-page-header bg-dark" style="background-image:url('<%= asset_path(@highlights_1.document.url) %>');background-attachment: fixed;">
        <div class="titan-caption">
          <div class="caption-content">

            <div class="font-alt titan-title-size-1" style="background-color: transparent;">
              <div class="module-subtitle font-serif animated fadeInUp" style="margin-top: 100px;"><%= @highlights_1.description %> </div>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</section>
<div class="main">
  <!-- ***********************************************************************   -->
  <section class="courses" id="events" data-aos="fade-up" data-aos-duration="1000">
    <div class="container">
      <div class="section-title">
        <p class="wow animated fadeInUp">Relax your mind with essence of nature</p>
        <h3 class="wow animated fadeInUp">Pick Your Trip</h3>

      </div>
      <div class="owl-carousel courses-carousel">
        <% @events.each do |event| %>
          <div class="card wow animated fadeInUp">
            <% if event.status == 'bookings_open' %>
              <div class="img-wrap book_now_2">
                <%= image_tag(event.document.url, :class => "card-img-top") if event.document %>
              </div>
            <% else %>
              <div class="img-wrap coming-soon">
                <%= image_tag(event.document.url, :class => "card-img-top") if event.document %>
              </div>
            <% end %>
            <div class="card-block">
              <span class="course-badge"><%= event.title.truncate(25, separator: ' ') %></span>
              <h5 class="card-title"><%= event.short_description.truncate(110, separator: ' ') %></h5>
              <hr>
              <p class="card-text date"><i class="fa fa-calendar" aria-hidden="true"></i> <%= event.start_date %></p>
              <p class="card-text price"><a href="<%= event_path(event) %>" class="btn-outline">View More</a></p>
            </div>
          </div>
        <% end %>
      </div>
      <br/>
      <p class="card-text price" style="text-align: center;"><a href="<%= events_path %>" class="btn-outline">Checkout All Events</a></p>
    </div>
  </section>
  <script>
    $(".courses-carousel").owlCarousel({
         loop: true,
         margin: 30,
         nav: true,
         smartSpeed: 500,
         dots: false,
         autoplay: true,
         responsive: {
             0: {
                 items: 1
             },
             600: {
                 items: 2,
                 width : '50%'
             },
             1000: {
                 items: 4
             }
         }
     });
  </script>
  <!-- ********************************************************************** -->
  <div class="container" id="Expedition">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3" style="margin-left: 25%; text-align:center;">
        <h2 class="module-title font-alt wow animated fadeInUp" style="margin-bottom:25px; margin-top:25px;">Expedition's</h2>
      </div>
    </div>
  </div>
  <section id="Section3" style="background:#e9ebee; padding-top:20px;">
    <div class="container">
      <div class="row" id="box-search">
        <a href="<%= event_path(@expedition_1) %>">
          <div class="thumbnail text-center col-md-6 wow animated fadeInLeft">
            <% if @expedition_1.status == 'bookings_open' %>
              <div class="img-wrap book_now_2">
                <%= image_tag(@expedition_1.document.url, :class => "card-img-top") if @expedition_1.document %>
              </div>
            <% else %>
              <div class="img-wrap coming-soon">
                <%= image_tag(@expedition_1.document.url, :class => "card-img-top") if @expedition_2.document %>
              </div>
            <% end %>

            <div class="caption">
              <h4 class="wow animated fadeInUp" data-wow-delay="0.5s" style="font-weight:bold;"><%= @expedition_1.title %></h4>
              <!-- <span class="wow animated fadeInUp" data-wow-delay="0.5s" style="color:#f00">COMING SOON</span> -->
            </div>
          </div>
        </a>
        <a href="<%= event_path(@expedition_2) %>">
          <div class="thumbnail text-center col-md-6 wow animated fadeInRight">
            <% if @expedition_2.status == 'bookings_open' %>
              <div class="img-wrap book_now_2">
                <%= image_tag(@expedition_2.document.url, :class => "card-img-top") %>
              </div>
            <% else %>
              <div class="img-wrap coming-soon">
                <%= image_tag(@expedition_2.document.url, :class => "card-img-top") %>
              </div>
            <% end %>
            <div class="caption wow animated fadeInUp" data-wow-delay="0.5s">
              <h4 class="wow animated fadeInUp" data-wow-delay="0.5s" style="font-weight:bold;"><%= @expedition_2.title %></h4>
              <!-- <span class="wow animated fadeInUp" data-wow-delay="0.5s" style="color:#f00">COMING SOON</span> -->
            </div>
          </div>
        </a>
      </div>
    </div>
  </section>
  <section class="module" id="aboutus" style="padding-top:80px;">
    <div class="container">
      <!-- <div class="row"> -->
      <!-- <div class="col-sm-8 col-sm-offset-3" style="margin-left: 17%;"> -->
      <!--<h2 class="module-title font-alt"></h2>-->
      <!-- <div class="module-subtitle font-serif">Explore Nature with Adventure, Learn From Natural Culture, Conservation through Exploration. IS WHAT WE DO. </div> -->
      <!-- </div> -->
      <!-- </div> -->
      <div class="row multi-columns-row">
        <div class="col-md-3 col-sm-6 col-xs-12 wow animated fadeInUp">
          <div class="features-item">
            <div class="features-icon"><span class="icon-profile-male"></span></div>
            <% who_we_are = instance_variable_get('@who_we_are') %>
            <h3 class="features-title font-alt"><%= who_we_are.key.humanize %></h3>
            <p><%= who_we_are.description %></p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 wow animated fadeInUp">
          <div class="features-item">
            <div class="features-icon"><span class="icon-gears"></span></div>
            <% what_we_do = instance_variable_get('@what_we_do') %>
            <h3 class="features-title font-alt"><%= what_we_do.key.humanize %></h3>
            <p><%= what_we_do.description %></p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 wow animated fadeInUp">
          <div class="features-item">
            <div class="features-icon"><span class="icon-tools"></span></div>
            <% from_whom_we_learn = instance_variable_get('@from_whom_we_learn') %>
            <h3 class="features-title font-alt"><%= from_whom_we_learn.key.humanize %></h3>
            <p><%= what_we_do.description %></p>
          </div>
        </div>
        <div class="col-md-3 col-sm-6 col-xs-12 wow animated fadeInUp">
          <div class="features-item">
            <div class="features-icon"><span class="icon-lightbulb"></span></div>
            <% what_we_learn = instance_variable_get('@what_we_learn') %>
            <h3 class="features-title font-alt"><%= what_we_learn.key.humanize %></h3>
            <p><%= what_we_learn.description %></p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="module" id="Gallery" style="padding-top:0px; padding-bottom:0px;">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt wow animated fadeInUp">Gallery</h2>
          <div class="module-subtitle font-serif"></div>
        </div>
      </div>
    </div>
    <div class="flex-container wow animated fadeInUp" style="padding-left:10px; padding-right:10px;">
      <div class="row multi-columns-row">
        <div class="gallery-carousel owl-carousel">
           <% 1.upto(6).each do |i| %>
             <% image = instance_variable_get("@gal_image_#{i}") %>
                    <div class="gallery-item">
                  <div class="gallery-image">
                    <a class="gallery" href="<%= asset_path(image.image.url) %>"> <%= image_tag image.image.url %>
                      <div class="gallery-caption">
                        <div class="gallery-icon">
                          <span class="icon-magnifying-glass"></span>
                        </div>
                    </a>
                </div>
              </div>
              </div>
           <% end %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>
</div>
</section>
<section class="bg-dark" style="padding-top: 22px;">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-md-8 col-lg-6 col-lg-offset-2 wow animated fadeInUp">
        <div class="callout-text font-alt">
          <h3 class="callout-title">Want to see more photos?</h3>
          <p>We are always open to interesting Adventures.</p>
        </div>
      </div>
      <div class="col-sm-6 col-md-4 col-lg-2 wow animated fadeInUp">
        <div class="callout-btn-box"><a class="btn btn-w btn-round" href="https://www.facebook.com/pg/AdventureCrusadersClub/photos/?ref=page_internal" target="_blank">Lets view portfolio</a></div>
      </div>
    </div>
  </div>
</section>
<section class="module" id="contact">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <h2 class="module-title font-alt wow animated fadeInUp">Get in touch</h2>
        <div class="module-subtitle font-serif"></div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-6 wow animated fadeIn">
        <%= form_tag contact_contact_admin_index_path do %>
          <div class="form-group">
            <label class="sr-only" for="name">Name</label>
            <%= text_field_tag :name, nil, :class => "form-control", :id => 'name', :placeholder => 'Your Name*', :required => true %>
            <p class="help-block text-danger"></p>
          </div>
          <div class="form-group">
            <label class="sr-only" for="name">Email</label>
            <%= email_field_tag :email, nil, :class => "form-control", :id => 'email', :placeholder => 'Your Email*', :required => true %>
            <p class="help-block text-danger"></p>
          </div>
          <div class="form-group">
            <label class="sr-only" for="message">Message</label>
            <%= text_area_tag :message, nil, :class => "form-control", :id => 'message', :placeholder => 'Your Message*', :required => true, :rows => "7" %>
            <p class="help-block text-danger"></p>
          </div>
          <div class="text-center">
            <%= submit_tag("Submit", :id => "cfsubmit", :class=> "btn btn-block btn-round btn-d", :name=>"submit") %>
          </div>
        <% end %>
      </div>
      <div class="col-sm-6 wow animated fadeIn">
        <h1>ADVENTURE CRUSADERS CLUB</h1>
        <h3>Mobile : <%= @contact_number %></h3>
        <h4>Email: <a href="mailto:<%= @email %>" style="color: blue"><%= @email %></a></h4>
        <h4>Address: <%= @address %></h4>
        <br />
        <div class="footer-social-links" style="font-size:30px;">
          <a href="https://www.facebook.com/AdventureCrusadersClub/" target="_blank" style="margin-left:20px;"><i class="fa fa-facebook"></i></a>
          <a href="https://twitter.com/club_crusaders" target="_blank" style="margin-left:20px;"><i class="fa fa-twitter"></i></a>
          <a href="https://www.youtube.com/playlist?list=PL-uI8xizMdLMFD3AANsA6tkBf447aB8c6" target="_blank" style="margin-left:20px;"><i class="fa fa-youtube"></i></a>
          <a href="https://www.instagram.com/adventurecrusadersclub/" target="_blank" style="margin-left:20px;"><i class="fa fa-instagram"></i></a>
        </div>
      </div>
    </div>
  </div>
</section>

</div>
</main>
<script>
  $(".gallery-carousel").owlCarousel({
       loop: false,
       margin: 30,
       nav: true,
       smartSpeed: 500,
       dots: false,
       autoplay: true,
       responsive: {
           0: {
               items: 1
           },
           600: {
               items: 2,
               width : '50%'
           },
           1000: {
               items: 3
           }
       }
   });
</script>

app/views/home/privacy_policy.html.erb
<div class="main">
  <!-- <section class="module bg-dark-60 about-page-header" data-background="<%= asset_path('privacy-policy.jpg') %>" style="padding: 100px 0;"> -->
 <!--  <section class="module bg-dark-60 about-page-header" data-background="<%= asset_path('privacy-policy.jpg') %>" style="padding: 100px 0;" background-image: url("<%= asset_path('privacy-policy.jpg') %>");>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt">PRICACY POLICY</h2>
        </div>
      </div>
    </div>
  </section> -->
  <section class="module pt-0 pb-0" id="about" style="margin-top:50px;">
    <div class="container">
      <div class="row">
        <!--<div class="col-xs-12 col-md-6 side-image" data-background="assets/images/section-14.jpg"></div>-->
        <div class="col-sm-12" style="text-align:justify;">
          <h3 class="module-title font-alt" style="margin-bottom:35px;">The Adventure crusader Club Privacy Policy</h3>
          <p style="font-size:14px;">This privacy policy covers how the Adventure Crusader Club uses personal information collected at this site. Please read this privacy policy before using the site or submitting any personal information. By using our site, you are accepting the practices described in this privacy policy. </p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">The Adventure crusader Club Privacy Policy</h5>
          <p style="font-size:14px;">This privacy policy covers how the Adventure Crusader Club uses personal information collected at this site. Please read this privacy policy before using the site or submitting any personal information. By using our site, you are accepting the practices described in this privacy policy. </p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">Collection of Information</h5>
          <p style="font-size:14px;">The  Adventure Crusader Club collects personally identifiable information, like names, postal addresses, email addresses, phone number etc., when you book a trip or take advantage of special offers. </p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">Distribution of Information</h5>
          <p style="font-size:14px;">We may share information with governmental agencies or other companies assisting us in fraud prevention or investigation. We may do so when: (1) permitted or required by law; or, (2) trying to protect against or prevent actual or potential fraud or unauthorized transactions; or, (3) investigating fraud which has already taken place. The information is not provided to these companies for marketing purposes. </p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">Third Party Partners and Suppliers:</h5>
          <p style="font-size:14px;">The  Adventure Crusader Club will share your information with the outside suppliers (such as guides, travel companies, hotel companies, insurance companies, and credit card processing entities etc, which perform services on our behalf. The Outdoor Adventure Club and its contracted suppliers never sell, lease or trade information about you or your travel information to other parties in the ordinary course of business.</p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">Commitment to Data Security</h5>
          <p style="font-size:14px;">Your personally identifiable information is kept secure. Only authorized employees, agents and contractors (who have agreed to keep information secure and confidential) have access to this information. All emails and newsletters from this site allow you to opt out of further mailings. </p>
          <h5 class="module-title font-alt" style="text-align:left; font-size:18px; margin-bottom:0px; font-weight:bold;">Privacy Contact Information</h5>
          <p style="font-size:14px;">We reserve the right to make changes to this policy. Any changes to this policy will be posted. If you have any questions, concerns, or comments about our privacy policy, please contact us at: </p>
          <p>
            Adventure Crusaders Club<br />
            #250, Shivakote, BLR-560089<br />
            Phone: 9164460041<br />
            Email: info@adventurecrusader.com
          </p>
        </div>
      </div>
    </div>
  </section>
</div>
</main>

app/views/home/terms_and_conditions.html.erb
<div class="main">
  <!-- <section class="module bg-dark-60 about-page-header" data-background="<%= asset_path('condition.jpg') %>" style="padding: 100px 0;" style="padding: 100px 0px;" background-image: url("<%= asset_path('condition.jpg') %>");>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt">TERMS & CONDITIONS</h2>
        </div>
      </div>
    </div>
  </section> -->
  <section class="module pt-0 pb-0" id="about" style="margin-top:50px;">
    <div class="container">
      <div class="row">
        <!--<div class="col-xs-12 col-md-6 side-image" data-background="assets/images/section-14.jpg"></div>-->
        <div class="col-sm-12" style="text-align:justify;">
          <h3 class="module-title font-alt" style="margin-bottom:35px;">The Adventure crusader Club Terms and Conditions</h3>
          <p style="font-size:14px;">On camping sites / During adventure activities </p>
          <p style="font-size:14px;">Participant(s)/Guardians should understand the risks involved in any adventure activity, before enrolling. </p>
          <p style="font-size:14px;">In case of any injury, sickness, accident, death or any other casualty or loss or damage of valuables or luggage or any equipment; organizers, volunteers or experts or any other person involved wholly or partially, either individually or jointly with Adventure Crusader Club shall not be responsible in any manner for the same and no claims of participants, parents, guardians, relatives or friends of participants will be entertained. </p>
          <p style="font-size:14px;">During the camp or treks or any adventure activity conducted by Adventure Crusader Club, participants shall abide by instructions and authorized representative of Adventure Crusader Club. </p>
          <p style="font-size:14px;">During the camps or treks or any adventure activity, the decision of authorized representative of Adventure Crusader Club shall be final and binding on all participants.</p>
          <p style="font-size:14px;">If participant(s) is found to disobey the directions/instructions of the authorized representative of Adventure Crusader Club, participant(s) shall be resposible for there own actions. </p>
          <p style="font-size:14px;">Participant(s) is responsible to inform the representative of Adventure Crusader Club regarding and medical conditions & disorders etc. arising during the program should be informed to the organizers.</p>
          <p>Any expenses for all medical treatment and arrangements made by the organizers for the participants will be solely borne by the participant.</p>
          <p>Consumption of liquor, tobacco products, cigarette etc. is strictly prohibited during the programs.</p>
          <p>Participant(s) should follow eco friendly behavior and respect nature i.e. avoids destruction of the flora and fauna, avoid throwing plastics in the places visited etc.</p>
          <h3 class="module-title font-alt" style="text-align:left; margin-bottom:10px;">Cancellation</h3>
          <p>    The request for cancellation and refund if any should be made in the Cancellation Form, duly signed by the traveler/guardian.</p>
          <p>Cancellation form will be available in the office during working days and during working hours.</p>
          <p>Refund will be paid by cheque only(not cash) within 15 days of event conclusion.</p>
          <p>    For cancellation of air tickets, rules of airline will be applied.</p>
          <p>Substitution of one person with another will be permitted where feasible and will be at the discretion of the management.</p>
          <p>    Adventure Crusader Club reserves all rights to modify/change any program/event.</p>
          <p>Adventure Crusader Club reserves all rights to cancel any event and in that case only, all fees accepted as “program fees/event fees” will be refunded within 15 working days after the date of cancellation.</p>
          <h3 class="module-title font-alt" style="text-align:left; margin-bottom:10px;">For any event  cancellation done by particepents below mentiond terms will be followed</h3>
          <p>    For more than 7 days prior to departure, 90% of the program fees will be refunded, or 100% amount can be remitted for future programs conducted within 3 months.</p>
          <p>For cancellation done more than 3 days and less than 7 days prior to the departure date, 50% of program fees will be refunded.</p>
          <p>No refund will be made if cancellation is made within 3 days prior to the departure date of event.</p>
          <p></p>
        </div>
      </div>
    </div>
  </section>
</div>
</main>