config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'terms_and_conditions', to: :show, controller: 'home'
  get 'privacy_policy', to: :show, controller: 'home'
  get 'download_csv', to: :show, controller: 'home'

  get "/checkout" => "checkout#index", as: :checkout
  post "/proceed-to-pay" => "payments#proceed_to_pay", as: :proceed_to_pay
  post "/order-processed" => "payments#order_processed", as: :order_processed
  get "/payment_success" => "payments#payment_success"

  resources :landing

  resources :events do
    resources :comments
  end
  resources :contact_admin do
    collection do
      post :contact
    end
  end
end

app/models/event.rb
class Event < ApplicationRecord
	mount_uploader :document, DocumentUploader

  after_save :set_tentative_schedules
  before_save :set_event_details

  has_many :comments, as: :commentable
  has_many :tentative_schedules, dependent: :destroy

  belongs_to :parent, :class_name => "Event", optional: true
  has_many :events, dependent: :destroy, :foreign_key => "parent_id"

  has_many :pick_up_points, dependent: :destroy
  accepts_nested_attributes_for :pick_up_points, allow_destroy: true
  accepts_nested_attributes_for :tentative_schedules, allow_destroy: true
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :documents, allow_destroy: true
  has_one :instructor_detail, dependent: :destroy
  accepts_nested_attributes_for :instructor_detail, allow_destroy: true

  enum event_type: %w(event course expedition)
  enum status: %w(coming_soon bookings_open ongoing completed)
  enum month: %w(January February March April May June July August September October November December)

  scope :past, -> { where('start_date < ?', Date.current).where.not(parent_id: nil) }
  scope :on_going, -> { where('start_date = ?', Date.current).where.not(parent_id: nil) }
  scope :future, -> { where('start_date > ?', Date.current).where.not(parent_id: nil) }
  scope :parent_events, -> { where(parent_id: nil) }

  amoeba do
    enable
  end

  private

  def set_tentative_schedules
    if tentative_schedules.blank? && event_type == 'event'
      tentative_schedules.create(key: 'Friday',
                                 value: "09:30 PM Pick-up from Indiranagar ESI Hospital, 09:45 PM Pick-up from New Shanthi Sagar hotel Domlur, 10:00 PM Pick-up from Lifestyle, Magrath road")
      tentative_schedules.create(key: 'Saturday',
                                 value: "06:30 AM Reach the place - Freshen up - Breakfast, 09:30 AM Trek from Sarpadhari to Mullyangiri, 02:00 PM Reach and Have packed lunch. Trek down to Bababuddhangiri, 07:00 PM Reach base camp - Dinner - Night stay")
      tentative_schedules.create(key: 'Sunday',
                                 value: "06:00AM Pack up things and Leave to water falls Reach water falls base and have fun Start back to Bangalore, 10:00PM Reach Bangalore")
    end
  end

  def set_event_details
    if event_type == 'event' || event_type.nil?
      self.what_to_pack = "Personal medication (if any),Strong backpack (Preferably water proof),Fresh pair of clothes for two days,Toiletries,Mosquito Reppellent Cream" if self.what_to_pack.blank?
      self.inclusions = "Forest permission charges,Non A/C Transport from Bangalore to Bangalore,Accommodation,Veg Meals (2 Breakfast 1 lunch & 1 Dinner),Basic First aid Support,Instructor" if self.inclusions.blank?
      self.exclusions = "Sunday Lunch, Snacks During Transit,Anything not mentioned above in Inclusion" if self.exclusions.blank?
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :find_event, only: [:show]

  def show
    @contact_number = Setting.find_by(key: 'contact_number').description
    @logo = Gallery.find_by(key: 'logo')
    @email = Setting.find_by(key: 'email').description
    @commentable = @event
    @comments = @commentable.comments
    @comment = Comment.new
  end

  def index
    @completed_events = Event.event.completed.where.not(parent_id: nil).group_by { |e| Event.months[e.month] }#.sort.to_h
    @bookings_open_events = Event.event.bookings_open.where.not(parent_id: nil).group_by { |e| Event.months[e.month] }#.sort.to_h
    @coming_soon_events = Event.event.coming_soon.where.not(parent_id: nil).group_by { |e| Event.months[e.month] }#.sort.to_h
    @ongoing_events = Event.event.ongoing.where.not(parent_id: nil).group_by { |e| Event.months[e.month] }#.sort.to_h
  end

  private

  def find_event
    @event = Event.find_by(id: params[:id])
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<div class="container" style="margin-right: 10%; margin-left: 8%; margin-top: 9% ; padding-right: 15%;">
  <h2 style="margin-left: 1.5%">
    <h2>Events</h2>
    <ul class="nav nav-tabs">
      <li class="active"><a data-toggle="tab" href="#bookings_open">Bookings Open</a></li>
      <li><a data-toggle="tab" href="#coming_soon">Coming Soon</a></li>
      <li><a data-toggle="tab" href="#ongoing">Ongoing</a></li>
      <li><a data-toggle="tab" href="#completed">Completed</a></li>
    </ul>
    <div class="tab-content">
      <div id="bookings_open" class="container tab-pane active"><br>
        <section class="home-section home-full-height" id="home bookings_open">
          <% if @bookings_open_events.present? %>
            <% @bookings_open_events.each do |key, values| %>
              <% if key %>
              	<h1><%= "Events in #{Event.months.invert[key]}" %></h1>
              <% end %>
              <% values.flatten.each_slice(3) do |events| %>
                <div class="row" style="margin-top: 20px; margin-right: 10%;">
                  <% events.each do |event| %>
                    <a href="<%= event_path(event) %>">
                      <div class="col-md-4">
                        <div class="column">
                          <div class="post-module">
                            <div class="thumbnail">
                              <%= image_tag event.document.url, :class => 'img-responsive' %>
                            </div>
                            <div class="post-content">
                              <!-- <a href="<%#= checkout_path({event_id: event.id}) %>">
                                <div class="category">Pay Now</div>
                              </a> -->
                              <a href="<%= event_path(event) %>">
                                <h1 class="title"><%= event.title.truncate(20) %></h1>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h2 class="sub_title"><%= event.duration ? event.duration : 'Not Available' %></h2>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <p class="description"><%= event.short_description.truncate(200) %></p>
                              </a>
                              <div class="post-meta"><span class="timestamp"><i class="fa fa-rupee"></i> <%= event.amount ? event.amount : 'Not Available' %></span>
                                <%= link_to "", event_path(event, :anchor => "disqus_thread"), :"data-disqus-identifer" => event.id %>
                                <a href="<%= event_path(event) %>"><span class=" pull-right" style="color: blue;">Read More</span></a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <h4 style="margin-left: 1%;">No Events to show</h4>
          <% end %>
        </section>
      </div>
      <div id="coming_soon" class="container tab-pane fade"><br>
        <section class="home-section home-full-height" id="home coming_soon">
          <% if @coming_soon_events.present? %>
            <% @coming_soon_events.each do |key, values| %>
              <% if key %>
              	<h1><%= "Events in #{Event.months.invert[key]}" %></h1>
              <% end %>
              <% values.flatten.each_slice(3) do |events| %>
                <div class="row" style="margin-top: 20px; margin-right: 10%;">
                  <% events.each do |event| %>
                    <a href="<%= event_path(event) %>">
                      <div class="col-md-4">
                        <div class="column">
                          <div class="post-module">
                            <div class="thumbnail">
                              <%= image_tag event.document.url, :class => 'img-responsive' %>
                            </div>
                            <div class="post-content">
                              <a href="#">
                                <div class="category">Coming Soon</div>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h1 class="title"><%= event.title.truncate(20) %></h1>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h2 class="sub_title"><%= event.duration ? event.duration : 'Not Available' %></h2>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <p class="description"><%= event.short_description.truncate(200) %></p>
                              </a>
                              <div class="post-meta"><span class="timestamp"><i class="fa fa-rupee"></i> <%= event.amount ? event.amount : 'Not Available' %></span>
                                <%= link_to "", event_path(event, :anchor => "disqus_thread"), :"data-disqus-identifer" => event.id %>
                                <a href="<%= event_path(event) %>"><span class=" pull-right" style="color: blue;">Read More</span></a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <h4 style="margin-left: 1%;">No Events to show</h4>
          <% end %>
        </section>
      </div>
      <div id="ongoing" class="container tab-pane fade"><br>
        <section class="home-section home-full-height" id="home ongoing">
          <% if @ongoing_events.present? %>
            <% @ongoing_events.each do |key, values| %>
              <% if key %>
              	<h1><%= "Events in #{Event.months.invert[key]}" %></h1>
              <% end %>
              <% values.flatten.each_slice(3) do |events| %>
                <div class="row" style="margin-top: 20px; margin-right: 10%;">
                  <% events.each do |event| %>
                    <a href="<%= event_path(event) %>">
                      <div class="col-md-4">
                        <div class="column">
                          <div class="post-module">
                            <div class="thumbnail">
                              <%= image_tag event.document.url, :class => 'img-responsive' %>
                            </div>
                            <div class="post-content">
                              <a href="#">
                                <div class="category">Ongoing</div>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h1 class="title"><%= event.title.truncate(20) %></h1>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h2 class="sub_title"><%= event.duration ? event.duration : 'Not Available' %></h2>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <p class="description"><%= event.short_description.truncate(200) %></p>
                              </a>
                              <div class="post-meta"><span class="timestamp"><i class="fa fa-rupee"></i> <%= event.amount ? event.amount : 'Not Available' %></span>
                                <%= link_to "", event_path(event, :anchor => "disqus_thread"), :"data-disqus-identifer" => event.id %>
                                <a href="<%= event_path(event) %>"><span class=" pull-right" style="color: blue;">Read More</span></a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <h4 style="margin-left: 1%;">No Events to show</h4>
          <% end %>
        </section>
      </div>
      <div id="completed" class="container tab-pane fade"><br>
        <section class="home-section home-full-height" id="home completed">
          <% if @completed_events.present? %>
            <% @completed_events.each do |key, values| %>
              <% if key %>
              	<h1><%= "Events in #{Event.months.invert[key]}" %></h1>
              <% end %>
              <% values.flatten.each_slice(3) do |events| %>
                <div class="row" style="margin-top: 20px; margin-right: 10%;">
                  <% events.each do |event| %>
                    <a href="<%= event_path(event) %>">
                      <div class="col-md-4">
                        <div class="column">
                          <div class="post-module">
                            <div class="thumbnail">
                              <%= image_tag event.document.url, :class => 'img-responsive' %>
                            </div>
                            <div class="post-content">
                              <a href="#">
                                <div class="category">Completed</div>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h1 class="title"><%= event.title.truncate(20) %></h1>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <h2 class="sub_title"><%= event.duration ? event.duration : 'Not Available' %></h2>
                              </a>
                              <a href="<%= event_path(event) %>">
                                <p class="description"><%= event.short_description.truncate(200) %></p>
                              </a>
                              <div class="post-meta"><span class="timestamp"><i class="fa fa-rupee"></i> <%= event.amount ? event.amount : 'Not Available' %></span>
                                <%= link_to "", event_path(event, :anchor => "disqus_thread"), :"data-disqus-identifer" => event.id %>
                                <a href="<%= event_path(event) %>"><span class=" pull-right" style="color: blue;">Read More</span></a></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                  <% end %>
                </div>
              <% end %>
            <% end %>
          <% else %>
            <h4 style="margin-left: 1%;">No Events to show</h4>
          <% end %>
        </section>
      </div>
    </div>
  </div>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <script type="text/javascript">
    $(window).load(function() {
      $('.post-module').hover(function() {
        $(this).find('.description').stop().animate({
          height: "toggle",
          opacity: "toggle"
        }, 300);
      });
    });
  </script>

app/views/events/show.html.erb
<div class="main">
  <% if @event.document.try(:url) %>
    <% image = asset_path(@event.document.url) %>
  <% else %>
    <% image = asset_path('black.jpeg') %>
  <% end %>
  <section class="module bg-dark-60 about-page-header" style="background-image: url(<%= image %>)">
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <h2 class="module-title font-alt"></h2>
          <div class="module-subtitle font-serif wow animated fadeInUp"><%= @event.title %><br/>
            <% if @event.documents.present? %>
              <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal" style="background: transparent; border-color: transparent;">Click to View Images</button>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
  <section class="module pt-0 pb-0" id="about" style="margin-top:25px;">
    <div class="container">
      <div class="page-body">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="module-title-x font-alt wow animated fadeInUp"><%= @event.title %>
              <%# if @event.status == 'bookings_open' %>
                <!-- (<a class="wow animated fadeInUp" style="color:blue;" href="<%#= checkout_path({event_id: @event.id}) %>">BOOK NOW</a>) -->
              <%# end %>
            </h3>
          </div>
          <div class="col-sm-12 wow animated fadeInUp">
            <div class="package-highlight">
              <ul class="list-inline">
                <li><span><%= @event.duration %></span></li>
                <li><span><%= @event.start_date.present? ? @event.start_date.strftime("%A") : "Date Not Available" %></span></li>
                <li><span><%= @event.amount %></span></li>
              </ul>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-9">
            <div class="row">
              <div class="col-sm-12">
                <p class="details-copy wow animated fadeIn">
                  <%= @event.full_description %>
                </p>
              </div>
            </div>
          </div>

            <div class="col-sm-3">

              <div class="book-highlight">
                <h4 class="wow animated fadeInUp">&#x20B9;  <%= @event.amount %></h4>
                <p class="text-center wow animated fadeIn">(Per Person, Including GST)</p>
              </div>

              <%# if @event.status == 'bookings_open' %>
                <!-- <div class="text-center">
                  <h5><a class="btn-outline wow animated fadeInUp"  href="<%#= checkout_path({event_id: @event.id}) %>">BOOK NOW</a></h5>
                </div> -->
              <%# end %>
              <div class="book-highlight">
                <% instructor_detail = @event.instructor_detail %>
                  <% if instructor_detail.present? && instructor_detail.user.present? %>
                    <div class="text-center">
                      <h3 class="wow animated fadeInUp"> <b>Instructor Details</b></h3>
                      <h6><b><i class="fa fa-user" aria-hidden="true"></i></b> <%= instructor_detail.user.full_name %></h6>
                      <h6><b><i class="fa fa-phone" aria-hidden="true"></i></b> <%= instructor_detail.user.contact_number %></h6>
                      <h6><b><i class="fa fa-envelope" aria-hidden="true"></i></b> <%= instructor_detail.user.email %></h6>
                    </div>
                  <% else %>
                    <div class="text-center"><h3> Instructor details will be updated soon</h3></div>
                  <% end %>
                </div>
            </div>





        </div>
      </div>
      <div class="row">
        <% if @event.tentative_schedules.present? %>
          <div class="col-sm-12 wow animated fadeInUp">
            <div class="module-subtitle font-alt text-leftx" style="margin-bottom:10px;">Tentative Schedule</div>
            <% @event.tentative_schedules.each do |tentative_schedule| %>
              <div class="timeline-item" date-is="<%= tentative_schedule.key %>">
                <h1></h1>
                <ul>
                  <% tentative_schedule.value.split(',').each do |text| %>
                    <li><%= text %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <blockquote class="wow animated fadeIn" style="    margin-top: 20px;">
              <p>Note: Drop points will be the same as pick-up points</p>
            </blockquote>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="row pack-desc">
    <div class="col-xs-12">
        <div class="col-md-4 wow animated fadeInUp">
      <div class="module-subtitle font-serif" style="margin-bottom:10px;">What to pack..?</div>
      <h3 style="">Always PACK LIGHT</h3>
      <ul>
        <% @event.what_to_pack.split(',').each do |text| %>
          <li><%= text %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-4 wow animated fadeInUp">
      <div class="module-subtitle font-serif" style="margin-bottom:10px;">Inclusions</div>
      <h3 style="">What is included in the tour</h3>
      <ul>
        <% @event.inclusions.split(',').each do |text| %>
          <li><%= text %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-md-4 wow animated fadeInUp">
      <div class="module-subtitle font-serif" style="margin-bottom:10px">Exclusions</div>
      <h3 style="text-align:left; ">What is NOT included in the tour</h3>
      <ul>
        <% @event.exclusions.split(',').each do |text| %>
          <li><%= text %></li>
        <% end %>
      </ul>
    </div>
    </div>
  
  </div>
</div>
</section>

<!-- <div class="comment-section container">
  <div class="col-sm-8 wow animated fadeInUp">
    <div id="disqus_thread"></div>
  </div>
  <script>

    var disqus_config = function () {
    };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = "https://adventurecrusaders-com.disqus.com/embed.js";
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div> -->

<%= render 'layouts/disqus' %>
</div>
</div>
</main>

<div class="container">
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header" style="text-align: center;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Gallery</h4>
        </div>
        <div class="modal-body ScrollStyle" style="text-align: center;">
          <div class="row" >
            <% @event.documents.each do |doc| %>
              <div class="col-md-4" style="margin-top:10px;">
                <%= image_tag doc.image.url, :style => "width:150px; height:150px;" %>
              </div>
            <% end %>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>