config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  get 'terms_and_conditions', to: :show, controller: 'home'
  get 'privacy_policy', to: :show, controller: 'home'
  get 'download_csv', to: :show, controller: 'home'

  get "/checkout" => "checkout#index", as: :checkout
  post "/proceed-to-pay" => "payments#proceed_to_pay", as: :proceed_to_pay
  post "/order-processed" => "payments#order_processed", as: :order_processed
  get "/payment_success" => "payments#payment_success"

  resources :landing

  resources :events do
    resources :comments
  end
  resources :contact_admin do
    collection do
      post :contact
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clone_event.rb
require 'csv'
class CloneEvent
  class << self
    def perform(event_id)
    	event = Event.find_by(id: event_id)
    	if event
	      event_dup = event.amoeba_dup
	      event_dup.parent_id = event.id
	      event_dup.document = event.document
	      event_dup.save
	      return event_dup
	    end
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/csv_db.rb
require 'csv'
class CsvDb
  class << self
    def convert_save(model_name, csv_data)
      csv_file = csv_data.read.gsub /\r/, ''
      parser = CSV.parse(csv_file).to_a
      parsed_contents = parser[1..-1]
      headers = parser[0].map(&:underscore)
      parsed_contents.each do |row|
        params = Hash[headers.zip(row.map { |i| i.force_encoding('UTF-8') if i.present? })]
        event = Event.new(params)
        event.save
      end
    end
  end
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :event
  mount_uploader :image, DocumentUploader
end

app/models/event.rb
class Event < ApplicationRecord
	mount_uploader :document, DocumentUploader

  after_save :set_tentative_schedules
  before_save :set_event_details

  has_many :comments, as: :commentable
  has_many :tentative_schedules, dependent: :destroy

  belongs_to :parent, :class_name => "Event", optional: true
  has_many :events, dependent: :destroy, :foreign_key => "parent_id"

  has_many :pick_up_points, dependent: :destroy
  accepts_nested_attributes_for :pick_up_points, allow_destroy: true
  accepts_nested_attributes_for :tentative_schedules, allow_destroy: true
  has_many :documents, dependent: :destroy
  accepts_nested_attributes_for :documents, allow_destroy: true
  has_one :instructor_detail, dependent: :destroy
  accepts_nested_attributes_for :instructor_detail, allow_destroy: true

  enum event_type: %w(event course expedition)
  enum status: %w(coming_soon bookings_open ongoing completed)
  enum month: %w(January February March April May June July August September October November December)

  scope :past, -> { where('start_date < ?', Date.current).where.not(parent_id: nil) }
  scope :on_going, -> { where('start_date = ?', Date.current).where.not(parent_id: nil) }
  scope :future, -> { where('start_date > ?', Date.current).where.not(parent_id: nil) }
  scope :parent_events, -> { where(parent_id: nil) }

  amoeba do
    enable
  end

  private

  def set_tentative_schedules
    if tentative_schedules.blank? && event_type == 'event'
      tentative_schedules.create(key: 'Friday',
                                 value: "09:30 PM Pick-up from Indiranagar ESI Hospital, 09:45 PM Pick-up from New Shanthi Sagar hotel Domlur, 10:00 PM Pick-up from Lifestyle, Magrath road")
      tentative_schedules.create(key: 'Saturday',
                                 value: "06:30 AM Reach the place - Freshen up - Breakfast, 09:30 AM Trek from Sarpadhari to Mullyangiri, 02:00 PM Reach and Have packed lunch. Trek down to Bababuddhangiri, 07:00 PM Reach base camp - Dinner - Night stay")
      tentative_schedules.create(key: 'Sunday',
                                 value: "06:00AM Pack up things and Leave to water falls Reach water falls base and have fun Start back to Bangalore, 10:00PM Reach Bangalore")
    end
  end

  def set_event_details
    if event_type == 'event' || event_type.nil?
      self.what_to_pack = "Personal medication (if any),Strong backpack (Preferably water proof),Fresh pair of clothes for two days,Toiletries,Mosquito Reppellent Cream" if self.what_to_pack.blank?
      self.inclusions = "Forest permission charges,Non A/C Transport from Bangalore to Bangalore,Accommodation,Veg Meals (2 Breakfast 1 lunch & 1 Dinner),Basic First aid Support,Instructor" if self.inclusions.blank?
      self.exclusions = "Sunday Lunch, Snacks During Transit,Anything not mentioned above in Inclusion" if self.exclusions.blank?
    end
  end
end

app/models/gallery.rb
class Gallery < ApplicationRecord
	mount_uploader :image, DocumentUploader
end

app/models/instructor_detail.rb
class InstructorDetail < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event
end

app/models/pick_up_point.rb
class PickUpPoint < ApplicationRecord
  belongs_to :event, optional: true
end

app/models/setting.rb
class Setting < ApplicationRecord
	mount_uploader :document, DocumentUploader
end

app/models/tentative_schedule.rb
class TentativeSchedule < ApplicationRecord
  belongs_to :event
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  has_one :user_payment_detail
  scope :success, -> { where(status: 'TXN_SUCCESS').order('created_at desc') }
  scope :failure, -> { where.not(status: 'TXN_SUCCESS') }
end

app/models/user.rb
class User < ApplicationRecord
	def full_name
		if last_name.present?
			name = first_name + " " + last_name
		else
			name = first_name
		end
		name
	end
end

app/models/user_payment_detail.rb
class UserPaymentDetail < ApplicationRecord
  belongs_to :payment_transaction, class_name: 'Transaction', foreign_key: :transaction_id, optional: true
  belongs_to :event
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :data_setting, only: %i(index)

  def terms_and_conditions
    @logo = Gallery.find_by(key: 'logo')
    @email = Setting.find_by(key: 'email').description
    @terms_and_conditions = Setting.find_by(key: 'terms_and_conditions')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def privacy_policy
    @email = Setting.find_by(key: 'email').description
    @logo = Gallery.find_by(key: 'logo')
    @contact_number = Setting.find_by(key: 'contact_number').description
  end

  def download_csv
    send_file(
      "#{Rails.root}/public/events_bulk.csv",
      filename: "events_bulk.csv"
    )
  end

  private

  def data_setting
    1.upto(3).map { |i| instance_variable_set("@highlights_#{i}", Setting.find_by(key: "Highlights#{i}")) }
    @email = Setting.find_by(key: 'email').description
    @address = Setting.find_by(key: 'address').description
    @contact_number = Setting.find_by(key: 'contact_number').description
    #1.upto(6).map { |i| instance_variable_set("@events_#{i}", Event.find_by(key: "Event#{i}")) }
    @events = Event.bookings_open.where.not(parent_id: nil)#.or(Event.coming_soon)
    1.upto(2).map { |i| instance_variable_set("@expedition_#{i}", Event.find_by(key: "Expedition#{i}")) }
    %w(who_we_are what_we_do from_whom_we_learn what_we_learn).each do |key|
    	instance_variable_set("@#{key}", Setting.find_by(key: key))
    end
    1.upto(6).map { |i| instance_variable_set("@gal_image_#{i}", Gallery.find_by(key: "GalImage#{i}")) }
    @gal_background = Gallery.find_by(key: "GalBackground")
    @logo = Gallery.find_by(key: 'logo')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_admin_helper.rb
module ContactAdminHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/clone/clone_event.html.erb
<%= form_for :clone_event, :url => { :action=>"clone_event" } do |f| %>
  <table>
    <tr>
      <td>Select Event :</td>
      <td>
        <%= f.select :event_id, options_for_select(Event.where(parent_id: nil).map { |e| [e.title, e.id] }), :class => 'genForm_dropBox' %>
      </td>
      <td>
        <%= submit_tag 'Submit' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/csv/upload_csv.html.erb
<%= form_for :dump, :url=> { :action=>"import_csv" }, :html => { :multipart => true } do |f| %>
  <table>
    <tr>
      <td>Select a CSV File :</td>
      <td>
        <%= f.file_field :file %>
      </td>
      <td>
        <%= submit_tag 'Submit' %>
      </td>
    </tr>
  </table>
<% end %>

app/views/layouts/_disqus.html.erb
<div class="comment-section container">
  <div class="col-sm-8 wow animated fadeInUp">
    <div id="disqus_thread"></div>
  </div>
  <script>
  var disqus_config = function () {
    this.page.url = "<%= request.original_url %>";
    this.page.identifier = "<%= request %>";
  };

  (function() {
    var d = document
    var s = d.createElement('script');
    s.src = 'https://18-191-55-84.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer bg-dark wow animated fadeInUp">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 wow animated fadeInUp">
        <p class="copyright font-alt">&copy; 2018&nbsp;<a href="index.html">Adventure Crusaders Club</a>, All Rights Reserved</p>
      </div>
      <div class="col-sm-6 wow animated fadeInUp">
        <div class="footer-social-links"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-dribbble"></i></a><a href="#"><i class="fa fa-skype"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>
<div class="scroll-up"><a href="#totop"><i class="fa fa-angle-double-up"></i></a></div>

app/views/layouts/_google_analytics.html.erb
<% if Rails.env == "production"  %>
<!-- <script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-126402967-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script> -->

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-126402967-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-126402967-1');
</script>

<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-custom navbar-transparent navbar-fixed-top one-page" role="navigation" style="padding-bottom:10px; background: #000;">
  <!-- <div class="containern animated fadeIn" style="text-align:right; padding-right: 70px; color:  #FFF; padding-top: 10px; padding-bottom:5px; text-transform:none; font-size:14px; padding-right: 5.5%;  margin-right: 5%"><i class="fa fa-envelope-o" aria-hidden="true"></i>
    <%#= @email %>  &nbsp;&nbsp;&nbsp;   <i class="fa fa-phone" aria-hidden="true"></i>
    <%#= @contact_number %>
  </div> -->
  <div class="container" style="border-top: 1px solid #555; border-bottom: 1px solid #555;">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#custom-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button><a class="navbar-brand animated fadeIn" href="<%= root_path %>" style="padding-top:4px; padding-bottom:57px;"><%= image_tag @logo.image.url %></a>
    </div>
    <div class="collapse navbar-collapse" id="custom-collapse">
      <ul class="nav navbar-nav navbar-right animated fadeInUp" style="padding-top:5px;">
        <li><a class="section-scroll" href="<%= root_path %>" style="padding-top:12px;"><i class="fa fa-home" aria-hidden="true" style="font-size:23px;"></i></a></li>
        <li class="dropdown"><a class="dropdown-toggle" href="<%= root_path %>" data-toggle="dropdown">About</a>
          <ul class="dropdown-menu">
            <li><a class="section-scroll" href="#aboutus">Who we are?</a></li>
            <li><a class="section-scroll" href="#Gallery">Gallery</a></li>
            <li><a class="" href="<%= terms_and_conditions_path %>" target="_blank">TERMS & CONDITIONS</a></li>
            <li><a class="" href="<%= privacy_policy_path %>" target="_blank">PRIVICY POLICY</a></li>
          </ul>
        </li>
        <li><a class="section-scroll" href="<%= root_path %>#events">Weekend Trips</a></li>
        <!-- <li><a class="section-scroll" href="<%= events_path %>#courses">Courses</a></li> -->
        <li><a class="section-scroll" href="<%= root_path %>#Expedition">Expedition</a></li>
        <li><a class="section-scroll" href="<%= root_path %>#contact">Contact us</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Adventure Crusaders</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed:400,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Volkhov:400i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.0/animate.min.css" />

    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.css" />
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script id="dsq-count-scr" src="//adventurecrusaders-com.disqus.com/count.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script>
    new WOW().init();
    </script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': false %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': false %>
  </head>

  <body>
    <%= render :partial => 'layouts/google_analytics' %>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>